#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTTP-CookieJar
Version  : 0.008
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/HTTP-CookieJar-0.008.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/HTTP-CookieJar-0.008.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libh/libhttp-cookiejar-perl/libhttp-cookiejar-perl_0.008-1.debian.tar.xz
Summary  : 'A minimalist HTTP user agent cookie jar'
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 MIT
Requires: perl-HTTP-CookieJar-license
Requires: perl-HTTP-CookieJar-man
Requires: perl(HTTP::Date)
Requires: perl(Test::Deep)
Requires: perl(Test::Requires)
Requires: perl(URI)
BuildRequires : perl(HTTP::Date)
BuildRequires : perl(Test::Deep)
BuildRequires : perl(Test::Requires)
BuildRequires : perl(URI)

%description
NAME
HTTP::CookieJar - A minimalist HTTP user agent cookie jar
VERSION
version 0.008

%package license
Summary: license components for the perl-HTTP-CookieJar package.
Group: Default

%description license
license components for the perl-HTTP-CookieJar package.


%package man
Summary: man components for the perl-HTTP-CookieJar package.
Group: Default

%description man
man components for the perl-HTTP-CookieJar package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n HTTP-CookieJar-0.008
mkdir -p %{_topdir}/BUILD/HTTP-CookieJar-0.008/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/HTTP-CookieJar-0.008/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-HTTP-CookieJar
cp LICENSE %{buildroot}/usr/share/doc/perl-HTTP-CookieJar/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-HTTP-CookieJar/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/HTTP/CookieJar.pm
/usr/lib/perl5/site_perl/5.26.1/HTTP/CookieJar/LWP.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-HTTP-CookieJar/LICENSE
/usr/share/doc/perl-HTTP-CookieJar/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/HTTP::CookieJar.3
/usr/share/man/man3/HTTP::CookieJar::LWP.3
